import type { RequiredDataFromCollectionSlug } from 'payload'

type ClinicData = Omit<RequiredDataFromCollectionSlug<'clinics'>, 'id' | 'createdAt' | 'updatedAt'>

export const clinicsData: ClinicData[] = [
  {
    name: 'Poradnia Chirurgii Ogólnej',
    shortDescription: 'Konsultacje i zabiegi chirurgiczne',
    icon: 'Scissors',
    slug: 'chirurgia-ogolna',
    sortOrder: 1,
    _status: 'published',
  },
  {
    name: 'Poradnia Urazowo-Ortopedyczna',
    shortDescription: 'Leczenie urazów i schorzeń kości',
    icon: 'Bone',
    slug: 'urazowo-ortopedyczna',
    sortOrder: 2,
    _status: 'published',
  },
  {
    name: 'Poradnia Ginekologiczno-Położnicza',
    shortDescription: 'Zdrowie kobiet i prowadzenie ciąży',
    icon: 'Baby',
    slug: 'ginekologia',
    sortOrder: 3,
    _status: 'published',
  },
  {
    name: 'Poradnia Kardiologiczna',
    shortDescription: 'Diagnostyka i leczenie chorób serca',
    icon: 'Heartbeat',
    slug: 'kardiologia',
    sortOrder: 4,
    _status: 'published',
  },
  {
    name: 'Poradnia Neurologiczna',
    shortDescription: 'Schorzenia układu nerwowego',
    icon: 'Brain',
    slug: 'neurologia',
    sortOrder: 5,
    _status: 'published',
  },
  {
    name: 'Poradnia Okulistyczna',
    shortDescription: 'Badanie wzroku i leczenie chorób oczu',
    icon: 'Eye',
    slug: 'okulistyka',
    sortOrder: 6,
    _status: 'published',
  },
  {
    name: 'Poradnia Otolaryngologiczna',
    shortDescription: 'Laryngologia dorosłych i dzieci',
    icon: 'Ear',
    slug: 'laryngologia',
    sortOrder: 7,
    _status: 'published',
  },
  {
    name: 'Poradnia Zdrowia Psychicznego',
    shortDescription: 'Pomoc psychologiczna i psychiatryczna',
    icon: 'Brain',
    slug: 'zdrowie-psychiczne',
    sortOrder: 8,
    _status: 'published',
  },
  {
    name: 'Poradnia Diabetologiczna',
    shortDescription: 'Leczenie cukrzycy i edukacja',
    icon: 'Drop',
    slug: 'diabetologia',
    sortOrder: 9,
    _status: 'published',
  },
  {
    name: 'Poradnia Gruźlicy i Chorób Płuc',
    shortDescription: 'Pulmonologia i spirometria',
    icon: 'Wind',
    slug: 'pulmonologia',
    sortOrder: 10,
    _status: 'published',
  },
  {
    name: 'Poradnia Reumatologiczna',
    shortDescription: 'Leczenie chorób reumatycznych',
    icon: 'Wheelchair',
    slug: 'reumatologia',
    sortOrder: 11,
    _status: 'published',
  },
  {
    name: 'Poradnia Medycyny Pracy',
    shortDescription: 'Badania profilaktyczne pracowników',
    icon: 'Briefcase',
    slug: 'medycyna-pracy',
    sortOrder: 12,
    _status: 'published',
  },
  {
    name: 'Poradnia Dermatologiczna',
    shortDescription: 'Dermatologia i wenerologia',
    icon: 'ScanSmiley',
    slug: 'dermatologia',
    sortOrder: 13,
    _status: 'published',
  },
  {
    name: 'Poradnia Terapii Uzależnień',
    shortDescription: 'Leczenie uzależnienia od alkoholu',
    icon: 'Pill',
    slug: 'terapia-uzaleznien',
    sortOrder: 14,
    _status: 'published',
  },
  {
    name: 'Diagnostyka Obrazowa',
    shortDescription: 'Pracownia RTG, USG i Tomografii',
    icon: 'Scan',
    slug: 'diagnostyka-obrazowa',
    sortOrder: 15,
    _status: 'published',
  },
  {
    name: 'Laboratorium Analityczne',
    shortDescription: 'Punkt pobrań i analityka medyczna',
    icon: 'Flask',
    slug: 'laboratorium',
    sortOrder: 16,
    _status: 'published',
  },
]
