import type { RequiredDataFromCollectionSlug } from 'payload'

type DepartmentData = Omit<RequiredDataFromCollectionSlug<'departments'>, 'id' | 'createdAt' | 'updatedAt'>

export const departmentsData: DepartmentData[] = [
  {
    name: 'Anestezjologii i Intensywnej Terapii',
    shortDescription: 'Całodobowa opieka nad pacjentami w stanie zagrożenia życia.',
    icon: 'WaveSine',
    slug: 'anestezjologia',
    isEmergency: false,
    sortOrder: 1,
    _status: 'published',
  },
  {
    name: 'Chirurgiczno - Urazowy',
    shortDescription: 'Zabiegi operacyjne, chirurgia urazowa oraz ginekologia.',
    icon: 'Scissors',
    slug: 'chirurgia',
    isEmergency: false,
    sortOrder: 2,
    _status: 'published',
  },
  {
    name: 'Dziecięcy',
    shortDescription: 'Kompleksowa diagnostyka i leczenie pacjentów pediatrycznych.',
    icon: 'Baby',
    slug: 'dzieciecy',
    isEmergency: false,
    sortOrder: 3,
    _status: 'published',
  },
  {
    name: 'Terapii Uzależnienia od Alkoholu',
    shortDescription: 'Terapia grupowa i indywidualna w trybie dziennym.',
    icon: 'Sun',
    slug: 'terapia-uzaleznien-dziennie',
    isEmergency: false,
    sortOrder: 4,
    _status: 'published',
  },
  {
    name: 'Geriatryczny',
    shortDescription: 'Specjalistyczna opieka nad osobami w podeszłym wieku.',
    icon: 'Users',
    slug: 'geriatria',
    isEmergency: false,
    sortOrder: 5,
    _status: 'published',
  },
  {
    name: 'Chorób Wewnętrznych',
    shortDescription: 'Diagnostyka i leczenie schorzeń internistycznych.',
    icon: 'Heartbeat',
    slug: 'choroby-wewnetrzne',
    isEmergency: false,
    sortOrder: 6,
    _status: 'published',
  },
  {
    name: 'Oddział Leczenia Uzależnień',
    shortDescription: 'Stacjonarna terapia uzależnień i wsparcie psychologiczne.',
    icon: 'Handshake',
    slug: 'leczenie-uzaleznien',
    isEmergency: false,
    sortOrder: 7,
    _status: 'published',
  },
  {
    name: 'Rehabilitacyjny',
    shortDescription: 'Rehabilitacja ogólnoustrojowa i neurologiczna.',
    icon: 'Wheelchair',
    slug: 'rehabilitacja',
    isEmergency: false,
    sortOrder: 8,
    _status: 'published',
  },
  {
    name: 'Szpitalny Oddział Ratunkowy',
    shortDescription: 'Pomoc w stanach nagłego zagrożenia życia 24/7.',
    icon: 'Ambulance',
    slug: 'sor',
    isEmergency: true,
    sortOrder: 0,
    _status: 'published',
  },
  {
    name: 'Zakład Opiekuńczo-Leczniczy',
    shortDescription: 'Długoterminowa opieka medyczna i pielęgnacyjna.',
    icon: 'House',
    slug: 'zol',
    isEmergency: false,
    sortOrder: 9,
    _status: 'published',
  },
  {
    name: 'Hospicjum Domowe',
    shortDescription: 'Opieka paliatywna sprawowana w warunkach domowych.',
    icon: 'Heart',
    slug: 'hospicjum',
    isEmergency: false,
    sortOrder: 10,
    _status: 'published',
  },
]
